# Generated by Django 4.2.13 on 2024-06-25 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dob_user_bio_user_gender_user_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
