# Generated by Django 4.2.13 on 2024-06-16 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='auth_log',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='security',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
