# Generated by Django 4.2.13 on 2024-06-25 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0004_alter_security_auth_log_alter_security_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipaddress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='security',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL),
        ),
    ]
